name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bazel-version: [8.1.0]
    steps:
      - uses: actions/checkout@v4
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - uses: bazel-contrib/setup-bazel@0.12.1
        with:
          bazelisk-version: 1.18.0
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: bazel
      - name: Set Bazel Version ${{ matrix.bazel-version }} .
        run: |
          echo ${{ matrix.bazel-version }} > .bazelversion 

      - name: bazelisk version
        run: |
          bazel version
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel-version }}

      - name: run example
        run: |
          bazel run --config=linux-platform --curses=no //example:hello_world
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel-version }}

      - name: run zlib_usage_example
        run: |
          # `rules_foreign_cc` must use `--spawn_strategy=local` to avoid downloading Bazel every time.
          bazel run --config=linux-platform --curses=no //third-party/zlib:zlib_usage_example --spawn_strategy=local
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel-version }}

      - name: sed linux_x86_64
        run: |
          sed -i.bak 's/\"\/\/toolchains\/platforms:linux_x86_64\",//g' toolchains/toolchains/toolchains.MODULE.bazel
          sed -i.bak 's/\"\/\/toolchains\/toolchains\/glibc_linux_x86_64:toolchains\",//g' toolchains/toolchains/toolchains.MODULE.bazel
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel-version }}

      - name: build luckfox example
        run: |
          bazel build --config=linux-luckfox-platform --curses=no //example:hello_world
          file bazel-bin/example/hello_world
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel-version }}

      - name: build luckfox zlib_usage_example
        run: |
          bazel build --config=linux-luckfox-platform --curses=no //third-party/zlib:zlib_usage_example
          file bazel-bin/third-party/zlib/zlib_usage_example
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel-version }}
